### ISSUE TITLE
Message: Tried to run command without establishing a connection

### ISSUE THREAD

**Issue by Pa55w0rd** [C4o/ChineseDarkWebCrawler#1]
Message: Tried to run command without establishing a connection
执行darkweb.py 报错
执行get_darkweb_pic_auto.py提示 	找不到image_id.txt

**Comment by C4o** [comment]
为了关闭后浏览器不会占用系统资源所以browser.close()后还用了browser.quit()，这边的message大概就是这边的问题，我之前测试没问题，兄弟可以把browser.quit()去掉。
第二个的话需要文件里有图片唯一id值才能爬取，第一个没运行成功，所以没有文件生成，建议看下代码。
