### ISSUE TITLE
执行了darkweb.py后，执行结果在哪看

### ISSUE THREAD

**Issue by panyhabc** [C4o/ChineseDarkWebCrawler#3]
项目可以正常跑完，但是执行后的数据在哪查看的？

**Comment by C4o** [comment]
darkweb.py是用来爬取中文暗网的信息并且进行分类入库的，其实逻辑就是登录-进首页-爬帖子的url-循环爬帖子-每个帖子的一些信息爬下来-入库，有个db.sqlite，是sqlite数据库，可以下个客户端打开看看。

**Comment by C4o** [comment]
哦对。。这个darkweb.py现在有一部分功能已经没用了，可以先抓下每个阶段的包然后改下或者干脆重写下。。不难的

**Comment by panyhabc** [comment]
好的，我试试看，多谢答复
