### ISSUE TITLE
ImportError: No module named web.settings

### ISSUE THREAD

**Issue by panyhabc** [C4o/ChineseDarkWebCrawler#4]
执行命令python manage.py runserver 127.0.0.1 8080不成功，提示错误ImportError: No module named web.settings。
在网上查找了一些解决方法，比如在wsgi.py 中添加下列语句：
path = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if path not in sys.path:
    sys.path.append(path)
os.environ['DJANGO_SETTINGS_MODULE'] = 'web.settings'
但还是存在该问题。

**Comment by C4o** [comment]
这个跟darkweb.py是分开的，这个就是个把darkweb.py入库的信息给读出来并且显示的一个django web，其实可以直接看sqlite的内容。

**Comment by panyhabc** [comment]
我是想能用则用，不想自己写了，哈哈

**Comment by xdx3000** [comment]
> 
> 
> 执行命令python manage.py runserver 127.0.0.1 8080不成功，提示错误ImportError: No module named web.settings。
> 在网上查找了一些解决方法，比如在wsgi.py 中添加下列语句：
> path = os.path.dirname(os.path.dirname(os.path.abspath(**file**)))
> if path not in sys.path:
> sys.path.append(path)
> os.environ['DJANGO_SETTINGS_MODULE'] = 'web.settings'
> 但还是存在该问题。

这是python2.7的问题吧。在web目录下新建一个 __init__.py 文件即可。
